// Generated by https://quicktype.io

class GameModel {
    int id;
    String slug;
    String name;
    String released;
    bool tba;
    String backgroundImage;
    double rating;
    int ratingTop;
    List<Rating> ratings;
    int ratingsCount;
    int reviewsTextCount;
    int added;
    AddedByStatus addedByStatus;
    int metacritic;
    int playtime;
    int suggestionsCount;
    String updated;
    dynamic userGame;
    int reviewsCount;
    String saturatedColor;
    String dominantColor;
    List<PlatformElement> platforms;
    List<ParentPlatform> parentPlatforms;
    List<Genre> genres;
    List<Store> stores;
    dynamic clip;
    List<Genre> tags;
    EsrbRating esrbRating;
    List<ShortScreenshot> shortScreenshots;

    GameModel({
        this.id,
        this.slug,
        this.name,
        this.released,
        this.tba,
        this.backgroundImage,
        this.rating,
        this.ratingTop,
        this.ratings,
        this.ratingsCount,
        this.reviewsTextCount,
        this.added,
        this.addedByStatus,
        this.metacritic,
        this.playtime,
        this.suggestionsCount,
        this.updated,
        this.userGame,
        this.reviewsCount,
        this.saturatedColor,
        this.dominantColor,
        this.platforms,
        this.parentPlatforms,
        this.genres,
        this.stores,
        this.clip,
        this.tags,
        this.esrbRating,
        this.shortScreenshots,
    });
}

class AddedByStatus {
    int yet;
    int owned;
    int beaten;
    int toplay;
    int dropped;
    int playing;

    AddedByStatus({
        this.yet,
        this.owned,
        this.beaten,
        this.toplay,
        this.dropped,
        this.playing,
    });
}

class EsrbRating {
    int id;
    String name;
    String slug;

    EsrbRating({
        this.id,
        this.name,
        this.slug,
    });
}

class Genre {
    int id;
    String name;
    String slug;
    int gamesCount;
    String imageBackground;
    String domain;
    Language language;

    Genre({
        this.id,
        this.name,
        this.slug,
        this.gamesCount,
        this.imageBackground,
        this.domain,
        this.language,
    });
}

enum Language { ENG }

class ParentPlatform {
    EsrbRating platform;

    ParentPlatform({
        this.platform,
    });
}

class PlatformElement {
    PlatformPlatform platform;
    String releasedAt;
    RequirementsEn requirementsEn;
    dynamic requirementsRu;

    PlatformElement({
        this.platform,
        this.releasedAt,
        this.requirementsEn,
        this.requirementsRu,
    });
}

class PlatformPlatform {
    int id;
    String name;
    String slug;
    dynamic image;
    dynamic yearEnd;
    int yearStart;
    int gamesCount;
    String imageBackground;

    PlatformPlatform({
        this.id,
        this.name,
        this.slug,
        this.image,
        this.yearEnd,
        this.yearStart,
        this.gamesCount,
        this.imageBackground,
    });
}

class RequirementsEn {
    String minimum;
    String recommended;

    RequirementsEn({
        this.minimum,
        this.recommended,
    });
}

class Rating {
    int id;
    String title;
    int count;
    double percent;

    Rating({
        this.id,
        this.title,
        this.count,
        this.percent,
    });
}

class ShortScreenshot {
    int id;
    String image;

    ShortScreenshot({
        this.id,
        this.image,
    });
}

class Store {
    int id;
    Genre store;

    Store({
        this.id,
        this.store,
    });
}
