// Generated by https://quicktype.io

class StoreModel {
    int? id;
    int? gameId;
    int? storeId;
    String? url;

    StoreModel({
        this.id,
        this.gameId,
        this.storeId,
        this.url,
    });
}
